# Generated by Django 4.2.2 on 2023-07-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeRawProjectQuasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("nivelacion", "Nivelación"),
                            ("gravterrabs", "Gravedad terrestre absoluta"),
                            (
                                "gravedades",
                                "Gravedades terrestres absolutas y relativas",
                            ),
                        ],
                        max_length=15,
                    ),
                ),
            ],
            options={
                "unique_together": {("id", "tipo")},
            },
        ),
    ]
