# Generated by Django 4.2.2 on 2023-07-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preprocesos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="typerawprojectquasi",
            options={
                "verbose_name": "tipo hijo del modelo quasi-geoidal",
                "verbose_name_plural": "tipos hijo del modelo quasi-geoidal",
            },
        ),
        migrations.AlterUniqueTogether(
            name="typerawprojectquasi",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="typerawprojectquasi",
            name="descripcion",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="typerawprojectquasi",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="typerawprojectquasi",
            name="tipo",
            field=models.CharField(choices=[], max_length=15, unique=True),
        ),
    ]
