# Generated by Django 4.2.2 on 2023-07-14 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("preprocesos", "0002_alter_typerawprojectquasi_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="typerawprojectquasi",
            old_name="descripcion",
            new_name="detalles",
        ),
    ]
