# Generated by Django 4.2.2 on 2023-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preprocesos", "0003_rename_descripcion_typerawprojectquasi_detalles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typerawprojectquasi",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("nivelacion", "Nivelación"),
                    ("gravterrabs", "Gravedad terrestre absoluta"),
                    ("gravedades", "Gravedades terrestres absolutas y relativas"),
                ],
                max_length=15,
                unique=True,
            ),
        ),
    ]
