# Generated by Django 4.2.2 on 2023-07-14 21:23

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("preprocesos", "0004_alter_typerawprojectquasi_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawProjectQuasiTerrain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "proyecto",
                    models.CharField(
                        choices=[("quasi-geoide", "Modelo Quasi-geoidal")],
                        max_length=20,
                    ),
                ),
                ("posicion", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos_crudos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "proyecto padre para proyecto geodésico",
                "verbose_name_plural": "proyectos para proyecto geodésico",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="RawProject",
        ),
    ]
