# Generated by Django 4.2.2 on 2023-07-14 22:04

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("preprocesos", "0006_alter_rawprojectquasiterrain_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawDataQuasiTerrain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "modelo padre de datos para proyecto geodeśico",
                "verbose_name_plural": "modelos padre de datos para proyecto geodésico",
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RawProjectQuasi",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "proyecto",
                    models.CharField(
                        choices=[("quasi-geoide", "Modelo Quasi-geoidal")],
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("terreno", "Observaciones en terreno"),
                            ("aerea", "Observaciones en avión"),
                            ("marina", "Observaciones en barco"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos_crudos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "proyecto hijo para el modelo quasi-geoidal",
                "verbose_name_plural": "proyectos hijos para el modelo quasi-geoidal",
            },
        ),
        migrations.DeleteModel(
            name="RawProjectQuasiTerrain",
        ),
    ]
