# Generated by Django 4.2.2 on 2023-07-15 17:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("preprocesos", "0007_rawdataquasiterrain_rawprojectquasi_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawDataQuasiAereo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "posicion",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("spring", models.DecimalField(decimal_places=3, max_digits=10)),
                ("beam", models.DecimalField(decimal_places=3, max_digits=10)),
                ("acc_hor", models.DecimalField(decimal_places=3, max_digits=10)),
                ("acc_vert", models.DecimalField(decimal_places=3, max_digits=10)),
                ("eotvos", models.DecimalField(decimal_places=3, max_digits=10)),
                ("altitud", models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                "verbose_name": "modelo hijo terrestre de datos para el modelo quasi-geoidal",
                "verbose_name_plural": "modelos hijos terrestres de datos para el modelo quasi-geoidal",
            },
        ),
        migrations.CreateModel(
            name="RawDataQuasiTerreno",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "posicion",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("elevacion", models.DecimalField(decimal_places=3, max_digits=10)),
                ("gravedad", models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                "verbose_name": "modelo hijo terrestre de datos para el modelo quasi-geoidal",
                "verbose_name_plural": "modelos hijos terrestres de datos para el modelo quasi-geoidal",
            },
        ),
        migrations.DeleteModel(
            name="RawDataQuasiTerrain",
        ),
        migrations.AlterModelOptions(
            name="rawprojectquasi",
            options={
                "verbose_name": "proyecto hijo terrestre crudo para el modelo quasi-geoidal",
                "verbose_name_plural": "proyectos hijos terrestres crudos para el modelo quasi-geoidal",
            },
        ),
        migrations.AddField(
            model_name="rawprojectquasi",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="rawprojectquasi",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
