# Generated by Django 4.2.2 on 2023-07-15 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("preprocesos", "0008_rawdataquasiaereo_rawdataquasiterreno_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawProjectQuasiAerea",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "proyecto",
                    models.CharField(
                        choices=[("quasi-geoide", "Modelo Quasi-geoidal")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "proyecto hijo terrestre crudo para el modelo quasi-geoidal",
                "verbose_name_plural": "proyectos hijos terrestres crudos para el modelo quasi-geoidal",
            },
        ),
        migrations.CreateModel(
            name="RawProjectQuasiTerreno",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "proyecto",
                    models.CharField(
                        choices=[("quasi-geoide", "Modelo Quasi-geoidal")],
                        max_length=20,
                    ),
                ),
                (
                    "data",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos_crudos_quasi_geoidales",
                        to="preprocesos.rawdataquasiterreno",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos_crudos_quasigeodales_terreno",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "proyecto hijo terrestre crudo para el modelo quasi-geoidal",
                "verbose_name_plural": "proyectos hijos terrestres crudos para el modelo quasi-geoidal",
            },
        ),
        migrations.RenameModel(
            old_name="RawDataQuasiAereo",
            new_name="RawDataQuasiAerea",
        ),
        migrations.DeleteModel(
            name="RawProjectQuasi",
        ),
        migrations.AddField(
            model_name="rawprojectquasiaerea",
            name="data",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proyectos_crudos_quasi_geoidales",
                to="preprocesos.rawdataquasiaerea",
            ),
        ),
        migrations.AddField(
            model_name="rawprojectquasiaerea",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proyectos_crudos_quasigeodales_aerea",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
