# Generated by Django 4.2.2 on 2023-07-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preprocesos", "0010_rawprojectquasiterreno_tipo_intersection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawprojectquasiterreno",
            name="origen_coordenadas",
            field=models.CharField(
                choices=[
                    ("nivelacion", "Coordenadas de nivelación"),
                    ("gravedad", "Coordenadas de gravedad"),
                ],
                default="original",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="typerawprojectquasi",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("nivelacion", "Nivelación"),
                    ("gravterrabs", "Gravedad terrestre absoluta"),
                    ("gravterrrel", "Gravedad terrestre relativa"),
                    ("gravedades", "Gravedades terrestres absolutas y relativas"),
                    (
                        "gravedades_nivelacion",
                        "Gravedades y nivelaciones intersectadas",
                    ),
                ],
                max_length=25,
                unique=True,
            ),
        ),
    ]
