# Generated by Django 4.2.2 on 2023-07-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preprocesos", "0012_remove_rawprojectquasiaerea_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawprojectquasiterreno",
            name="archivo_origen",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
