# Generated by Django 4.2.2 on 2023-07-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preprocesos", "0013_rawprojectquasiterreno_archivo_origen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdataquasiterreno",
            name="nomenclatura",
            field=models.CharField(max_length=20),
        ),
    ]
