# Generated by Django 4.2.2 on 2023-07-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("preprocesos", "0015_rawprojectquasiterreno_tipo_proyecto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawprojectquasiterreno",
            name="tipo_proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proyectos_crudos_quasigeodales_terreno_tipo_proyecto",
                to="preprocesos.typerawprojectquasi",
            ),
        ),
    ]
