# Generated by Django 4.2.2 on 2023-07-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subirarchivo",
            options={
                "ordering": ("-id",),
                "verbose_name": "archivo crudo subido",
                "verbose_name_plural": "archivos crudos subidos",
            },
        ),
        migrations.AlterField(
            model_name="subirarchivo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("nivelacion", "Nivelación"),
                    ("gravterrabs", "Gravedad terrestre absoluta"),
                    ("gravterrabs", "Gravedad terrestre relativa"),
                    ("gravedades", "Gravedades terrestres absolutas y relativas"),
                ],
                max_length=20,
            ),
        ),
    ]
