# Generated by Django 4.2.2 on 2023-07-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0002_alter_subirarchivo_options_alter_subirarchivo_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subirarchivo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("nivelacion", "Nivelación"),
                    ("gravterrabs", "Gravedad terrestre absoluta"),
                    ("gravterrrel", "Gravedad terrestre relativa"),
                    ("gravedades", "Gravedades terrestres absolutas y relativas"),
                ],
                max_length=20,
            ),
        ),
    ]
