# Generated by Django 4.2.2 on 2023-07-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0003_alter_subirarchivo_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subirarchivo",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
